 

# Handbook structure <a name="handbook_structure"></a>

key words:  input, output, FIGURE, TABLE, 

TO DO LIST

1. replace ReporteRs with officer; 
2. use both rmarkdown report template or officer word-based template to include ALL;
3. model-development tree structure, borrow pirana idea
4. NEED EXTRT FROM ADEX, to cascade all to all rows? if not, some figure title need that information.
5. add sigmoid curve fitting





BUGS report
1. use descriptive anlaysis to generate plots, but fail to show up at review; 
2. 







```{r, eval=FALSE}
library(fakeDataWithError)
tdata = tdata %>% mutate(TIME=as_numeric(TIME), 
                         DVOR = as_numeric(DVOR)
                         )

tdata$DVOR = +  add_prop_uniform(1,  tdata$DVOR, u_sd=0, p_sd=0.2)

```


## Build dataset <a name="struct_run_sim"></a>

Under 10_construct_dataset.Rmd, 

1. callModule(module_build_dataset_wrapper) for   
    + module_load_dataset
    + module_build_dataset 
     
    + module_build_dataset::module_save_data;
    + module_build_dataset::module_checkInCols; 
    + module_build_dataset::module_checkInRows; 
  

## descriptive_analysis

module_load_dataset
module_run_script




## Model development <a name="struct_model_development"></a>

Under model_development.Rmd (bookmark: model_diagnostic), 

1. Under model_development.Rmd,    
    + module_runsim::module_load_cppModel
    + module_runsim::module_runsim_adsl;
    
    
to do list: 
    + check the status of cluster using qstat and qhost
    + decision tree for model development  
    
    
    
2. Model diagnostics Under model__diagnostic.Rmd, 
    + select program and job, then load the corresponding **xpdb**;   **may join with meta information **
    **use TEST as program and use LN102_DAT1 as the job name**  
    + generate all pre-defined diagnostic plots **[note to be redo]**, then 
    + call module_model_diagnostic_predefined::GOF1, GOF2, GOF3, etc.
    
    + useing loaded **xpdb** then callModule(module_run_script) 
    + module_run_script::GOF1, GOF2, GOF3; 
  
    
        


## Run simulation <a name="struct_run_sim"></a>

Under run_sim.Rmd, 

1. callModule(module_runsim) for   
    + module_runsim::module_load_dataset::module_save_data;
    + module_runsim::module_load_cppModel;
    + module_runsim::module_runsim_adsl;
    + module_runsim::module_runsim_adex; 
    + module_runsim::module_runsim_setting; [not used anymore]
    + module_runsim::module_runsim_output:module_run_script 
    
2. callModule(module_load_dataset) then  
    + module_run_script::summarise_exposure;
    + module_run_script::pct_threshold; 
    + module_run_script::plot_VPC; 
  
    + module_save_data::download; 
    + module_save_table::download; 
    + module_save_figure::module_ggplot_brush::download; 

 to do list: 
    + auto-translate nonmem model to mrgsolve cpp model
    
