---
title: "An Interactive Handbook for Pharmacometrics Analysis"
author: "Feng Yang"
date: '`r format(Sys.time(), "%d %B, %Y")`'
documentclass: book
runtime: shiny
output: 
  bookdown::html_document2:
    toc: yes
    toc_depth: 3    
    number_sections: yes
    keep_md: no
    code_folding: show
    fig_caption: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  bookdown::word_document2:
    reference_docx: template.docx
    fig_width: 4
    fig_height: 3
    fig_caption: true
    toc: yes
    toc_depth: 3    
    number_sections: yes
  bookdown::pdf_document2:
    toc: true
    number_sections: true
bibliography: [articleFWM.bibtex]
biblio-style: apalike
pandoc_args: [ "--csl", "hydrological-processes.csl" ]
link-citations: yes
resource_files:
- rmd/01_preface/01_preface.Rmd
- rmd/02_construct_dataset/01_construct_dataset.Rmd
- rmd/03_integrity_check/01_load_data.Rmd
- rmd/03_integrity_check/02_quick_check.Rmd
- rmd/03_integrity_check/03_advanced_check.Rmd
- rmd/03_integrity_check/04_buildIn_model.Rmd
- rmd/04_summary_dataset/01_summary_dataset.Rmd
- rmd/05_descriptive_analysis/01_stdtimeprofile.Rmd
- rmd/05_descriptive_analysis/02_pkpd_relationship.Rmd
- rmd/05_descriptive_analysis/03_NCA_analysis.Rmd
- rmd/06_run_ctl/01_run_nonmem_model.Rmd
- rmd/06_run_ctl/02_model_diagnostic.Rmd
- rmd/07_run_cpp/01_run_sim.Rmd
- rmd/08_exposure_response/01_exposure_response.Rmd
- rmd/09_advanced_model/01_advanced_model.Rmd
- rmd/10_reporting/01_reporting.Rmd
- rmd/90_appendix/01_global_setting.Rmd 
- rmd/90_appendix/01_model_library.Rmd
- rmd/90_appendix/02_dplyr.Rmd
- rmd/90_appendix/03_ggplot.Rmd
- rmd/90_appendix/04_mrgsolve.Rmd
- rmd/90_appendix/05_tools.Rmd 
- rmd/references.Rmd
- module/module_build_dataset.R
- module/module_build_dataset_wrapper.R
- module/module_check_nmdat_status.R
- module/module_checkInCols.R
- module/module_checkInRows.R
- module/module_checkOut.R
- module/module_fetch_job.R
- module/module_ggplot_brush.R
- module/module_linked_profiles.R
- module/module_load_cppModel.R
- module/module_load_ctlModel.R
- module/module_load_data.R
- module/module_load_dataset.R
- module/module_model_diagnostic_predefined.R
- module/module_review.R
- module/module_review_cppModel.R
- module/module_review_ctlModel.R
- module/module_review_script.R
- module/module_run_script.R
- module/module_runsim.R
- module/module_runsim_adex.R
- module/module_runsim_adsl.R
- module/module_runsim_ouput.R
- module/module_runsim_setting.R
- module/module_save_data.R
- module/module_save_figure.R
- module/module_save_table.R
- module/module_submit_job.R
- module/module_tabBox_next_previous.R
- module/module_table_output.R
- module/module_update_cppModel.R
- module/module_update_ctlModel.R
- module/module_visnetwork.R
- module/module_visnetwork_model_development.R
- module/module_visnetwork_model_library.R
- script/build_adex.R
- script/build_adpc.R
- script/build_adpx.R
- script/build_adsl.R
- script/build_nmdat.R
- script/descriptive_PKPD_hysterisis.R
- script/descriptive_PKPD_sigmoid.R
- script/descriptive_time_profile_indiv.R
- script/descriptive_time_profile_mean.R
- script/runSim_by_script.R
- script/simdata_pct_threshold.R
- script/simdata_plot_VPC.R
- script/simdata_summary_exposure.R
- script/simdata_summary_exposure_v2.R
- script/user_specified_diagnostic_plot_GOF1.R
- script/user_specified_diagnostic_plot_GOF2.R
- script/user_specified_diagnostic_plot_GOF3.R
- script/xpdb_diagnostic_ETAvsCOV.R
- script/xpdb_diagnostic_ETAvsETA.R
- script/xpdb_diagnostic_GOF1.R
- script/xpdb_diagnostic_GOF2.R
- script/xpdb_diagnostic_GOF3.R
- data/adex.csv
- data/adsl.csv
- data/adpc.csv
- data/other.csv
- data/nmdatPK.csv
- data/nmdatPKPD.csv
- ctl/LN001.ctl
- ctl/LN002.ctl
- ctl/MM001.ctl
- cpp/library/effect.cpp
- cpp/library/emax.cpp
- cpp/library/modpk2po.cpp
- cpp/library/pk1cmt.cpp
- cpp/library/pk2cmt.cpp
- cpp/library/pk3cmt.cpp
- cpp/library/pkpdExample.cpp
- cpp/library/popex.cpp
- cpp/library/popExample.cpp
- cpp/library/tmdd.cpp
- cpp/LN001.cpp
- cpp/MM001.cpp
- lib/pkmeta.xlsx
- lib/pkmeta_old.xlsx
- util/ggplot/add_formula_pvalue.R
- util/ggplot/base_histgram.r
- util/ggplot/base_scatter.r
- util/ggplot/base_theme.R
- util/ggplot/cat_boxplot.R
- util/ggplot/doublePanelPlot.r
- util/ggplot/doubleYPlot.r
- util/ggplot/ggpaircor.R
- util/ggplot/multiplot.R
- util/ggplot/setup_scale.R
- util/ggplot/zzz.r
- util/modeldev/all_function.R
- util/modeldev/check_run_status.R
- util/modeldev/fetch_job_from_HPC.R
- util/modeldev/list_folder_on_HPC.R
- util/modeldev/read_runno.R
- util/modeldev/read_runSummary_table.R
- util/modeldev/run_command_on_HPC.R
- util/modeldev/submit_job_to_HPC.R
- util/modeldev/util_dev.r
- util/mrgsolve/create_event.R
- util/mrgsolve/event_add_adsl.R
- util/mrgsolve/process_event.R
- util/mrgsolve/runSim_by_dosing_regimen.R
- util/mrgsolve/sim_timept.R
- util/mrgsolve/util_sim.r
- util/nmdat/extract_nmdat_name.R
- util/nmdat/fillUpCol_df.R
- util/nmdat/fuzzy_match.R
- util/nmdat/parseARMA.R
- util/nmdat/parseExpr.R
- util/nmdat/parseTIMEPT.R
- util/nmdat/read_datafile.R
- util/nmdat/standardise_SAMDTTM.R
- util/nmdat/standardise_USUBJID.R
- util/pkparams/calc_half_life.R
- util/pkparams/util_pk.r
- util/reporteR/addParagraph2.R
- util/reporteR/docAcctTab.r
- util/reporteR/docCoverPage.r
- util/reporteR/docPKPD.r
- util/reporteR/docStdProfile.r
- util/reporteR/myFlexTable.R
- util/reporteR/print_title_footnote.R
- util/reporteR/print2_word_ppt.R
- util/reporteR/vanilla_table.R
- util/rmarkdown/runAllChunks.R
- util/shinyPMx/best_guess.R
- util/shinyPMx/determineCurrentUser.R
- util/shinyPMx/plotIt.R
- util/stat/basic_stats.R
- util/stat/calc_stats.R
- util/stat/summary_of_studies.R
- util/util/add_prefix.R
- util/util/as_numeric.R
- util/util/as_time.R
- util/util/assign_Q.R
- util/util/colAttr.R
- util/util/colFmt.R
- util/util/colScheme.R
- util/util/convert_vars_type.R
- util/util/empty_canvas.R
- util/util/lmp.R
- util/util/merge_all.R
- util/util/order_cols.R
- util/util/spread_n.R
- util/util/strVec2matrix.R
- util/util/try_eval.R
- util/util/u_find_first_occurrence.R
- util/util/u_signif.R
- util/util/util.r
- util/xpose/GOF_PD1.R
- util/xpose/util_xpose.r
---


```{r, setup_handbook, include=FALSE}
#----------------------------------------
# to reload R file in case updating
#----------------------------------------

# This is a collection of Shiny examples.
#https://github.com/rstudio/shiny-examples


#https://www.brodrigues.co/blog/2018-10-05-ggplot2_purrr_officer/


# https://www.pharmasug.org/proceedings/china2018/AD/Pharmasug-China-2018-AD38.pdf
#@ https://community.rstudio.com/t/best-practices-for-organizing-rmarkdown-projects/914/2
# http://www.dartistics.com/rmarkdown-shiny.html
#@ http://dannyjnwong.github.io/blog/

# a bookdown template that works perfectly!  07-28-2019
# https://francoisbirgand.github.io/template-bookdown-article.html

# https://adv-r.hadley.nz/evaluation.html


#HOME <- paste0(getwd(), "/")
#HOME = paste0(normalizePath("."), "/")
source(paste0("./global.R"))
WORKING_HOME = HANDBOOK_HOME
HOME = HANDBOOK_HOME

options(digits = 4)


# I found this function that loads a list of packages using 'library', and installs them if they are not installed. 
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, library, character.only = TRUE)
}

# usage
# packages <- c("knitr", "captioner", "stringr", "devtools", "bookdown","kableExtra")
# ipak(packages)
 
file.lst <- list_files_in_a_folder(folder.loc=paste0(HOME, "/util/"), file.extension=c(".r", ".R"))
for (ifile in 1:length(file.lst)) {source(file=file.lst[ifile]) }     

file.lst <- list_files_in_a_folder(folder.loc=paste0(HOME, "/module/"), file.extension=c(".r", ".R"))
for (ifile in 1:length(file.lst)) {source(file=file.lst[ifile])  }     
 
file.lst <- list_files_in_a_folder(folder.loc=paste0(HOME, "/script/"), file.extension=c(".r", ".R"))
for (ifile in 1:length(file.lst)) {source(file=file.lst[ifile])  }     

```


 
 
```{r}
ALL <- reactiveValues(
  DATA   = default_DATA, 
  FIGURE = default_FIGURE, 
  TABLE = default_TABLE, 
  cppModel = default_cppModel, 
  ctlModel = default_ctlModel, 
  script = default_script
)  
```



```{r eval=FALSE}
rmd <- list.files(pattern = '*.Rmd', recursive = T)
chunks <- paste0("```{r child = './", rmd, "'}\n```\n")
cat(chunks, sep = '\n')
```
 

```{r child = './rmd/01_preface/01_preface.Rmd'}
```

```{r child = './rmd/02_construct_dataset/01_construct_dataset.Rmd'}
```

```{r child = './rmd/03_integrity_check/01_load_data.Rmd'}
```

```{r child = './rmd/03_integrity_check/02_quick_check.Rmd'}
```

```{r child = './rmd/03_integrity_check/03_advanced_check.Rmd'}
```

```{r child = './rmd/03_integrity_check/04_buildIn_model.Rmd'}
```

```{r child = './rmd/04_summary_dataset/01_summary_dataset.Rmd'}
```

```{r child = './rmd/05_descriptive_analysis/01_stdtimeprofile.Rmd'}
```

```{r child = './rmd/05_descriptive_analysis/02_pkpd_relationship.Rmd'}
```

```{r child = './rmd/05_descriptive_analysis/03_NCA_analysis.Rmd'}
```

```{r child = './rmd/06_run_ctl/01_run_nonmem_model.Rmd'}
```

```{r child = './rmd/06_run_ctl/02_model_diagnostic.Rmd'}
```

```{r child = './rmd/07_run_cpp/01_run_sim.Rmd'}
```

```{r child = './rmd/08_exposure_response/01_exposure_response.Rmd'}
```

```{r child = './rmd/09_advanced_model/01_advanced_model.Rmd'}
```

```{r child = './rmd/10_reporting/01_reporting.Rmd'}
```

```{r child = './rmd/90_appendix/01_global_setting.Rmd'}
```

```{r child = './rmd/90_appendix/01_model_library.Rmd'}
```

```{r child = './rmd/90_appendix/02_dplyr.Rmd'}
```

```{r child = './rmd/90_appendix/03_ggplot.Rmd'}
```

```{r child = './rmd/90_appendix/04_mrgsolve.Rmd'}
```

```{r child = './rmd/90_appendix/05_tools.Rmd'}
```
 

```{r child = './rmd/references.Rmd'}
```




```{r}
#https://stackoverflow.com/questions/6535927/how-do-i-prevent-rplots-pdf-from-being-generated
pdf(NULL)
```

 
