## Applications

Some _significant_ applications are demonstrated in this chapter.
 
 
 
 
```{r}
file.name = paste0(HOME, "/data/nmdat_PKPD_1024_2018.csv")
nmdat = read_csv(file.name, 
                 col_type=cols(.default=col_character()))   # read as character as defualt


nmdat <- nmdat %>% 
  mutate(ARMA = gsub("_", " ", ARMA, fix=TRUE), 
         ARMA = ordered(ARMA, levels=unique(as.character(ARMA))), # make ARMA as a ordered factor
         ARMAN = as.integer(ARMA), 
         TIME=as.numeric(TIME), 
         DV   = as.numeric(DV),
         DVOR = as.numeric(DVOR), 
         ID = as.integer(ID), 
         TIME = as.numeric(TIME), 
         AMT = as.numeric(AMT),  ################
         RATE = as.numeric(RATE), 
         EVID = as.integer(EVID), 
         CMT = as.integer(CMT), 
         MDV = as.integer(MDV), 
         NTIM = as.numeric(NTIM),
         LLOQ = as.numeric(LLOQ)
         
         
         #WGTBL = as.numeric(WGTBL),
         #CH50HBL = as.numeric(CH50HBL), 
         #C5BL = as.numeric(C5BL) 
)

 
```
  


 
```{r, eval=TRUE} 

  mydata = nmdat%>%filter(TEST%in%c("REGN3918", "CH50H"))
    
  fig = ggplot(mydata, aes(x=TIME, y=DVOR, group=ID, col=ARMA)) + 
    geom_point() + geom_line()  + facet_wrap(~TEST,ncol=1)
  
   

   callModule(ggplot_brush, "myggplot_pkpd", 
                  fig, mydata=mydata, xvar="TIME", yvar="DVOR")

  renderUI({ 
    ggplot_brush_Input(id="myggplot_pkpd", label = "myggplot_brush")
 
  })
 
```




