 

# Descriptive analysis  <a name="descriptive_analysis"></a>

This chapter is dedicated for all data-driven pharmacokinetics/pharmacodynmaic analysis, with a minimum level
of modeling.  Most often, the concentration-time profiles will be plotted, in both log- and linear-scale.  A variety of visualization are presented for PK-PD analyses. 

## Time-profile 

```{r}

  actionButton.style ="float:left;color: #fff; background-color: #328332; border-color: #328332"

  # some global variables that will be used in subsequent analysis.
  STUDY.NAME = "Study R3918-HV-1659"
  
  DRUG.NAME = "Pozelimab"   # REGN3918"
  
  PK.TEST.NAME = "REGN3918"
  PK.TEST.LABEL = "Total Pozelimab"   # Total REGN3918"
  
  TARGET.TEST.NAME = "C5"
  TARGET.TEST.LABEL = "Total C5"
  
  PD.TEST.NAME = "CH50H"
  PD.TEST.LABEL = "CH50"
  
  PD.PCHG.LABEL = "Percent Change from Baseline in CH50"
 
  


```

  
 
  
```{r}
#----------------------------------------------------
# load_nmdat_container
#----------------------------------------------------
output$despcriptive_analysis_data_selector <-renderUI({
   
  # callModule 
  #isolate({ 
    ALL = callModule(module_load_dataset, "load_nmdat_for_despcriptive_analysis", 
                     ALL, dataset_name="mYtEsT_for_despcriptive_analysis")
 # })
  
  # UI  
  fluidRow(column(6, 
                   module_load_dataset_UI(id="load_nmdat_for_despcriptive_analysis", label=NULL)
                 ), 
            column(6, 
                   HTML(colFmt("internal library: build-in dataset <br>
                                within session: secondary data derived from the original <br> 
                                external file: external file", color="gray")
                        )
                   )
            )  
  })
  fluidRow(column(12, uiOutput(("despcriptive_analysis_data_selector"))))
```