 
## PKPD relationship <a name="despcriptive_PKPD"></a>

 
 
### Linked PK/PD time-profile
 
 
```{r}
  
  #--------------------------------------  
  # load_internal_ctlModel_container
  #-------------------------------------- 
  output$select_multiple_response_variables_4PKPD_container <- renderUI({
    validate(need(globalVars$login$status, message=FALSE)) 
    
    tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
    validate(need(tdata, message="no data found yet"))
    
    # testcat.lst = unique(tdata$TESTCAT)
    # testcat.lst = testcat.lst[which(substr(testcat.lst, 1, 4)=="RESP")]
    # 
    # validate(need(tdata, message="no data found yet"), 
    #          need("TESTCAT" %in% colnames(tdata), message="missing TESTCAT variable"), 
    #          need(testcat.lst, message="no RESP variable found")
    # )
    # 
    # testcat.lst = c("", sort(testcat.lst) )
    TEST_lst <- tdata$TEST %>% unique()
    
    tagList(
    fluidRow( 
      column(12, 
             style='margin-bottom:30px;  border:1px solid; padding: 10px;',
             
        fluidRow(
          column(6,  
             selectizeInput("xvar_name", 
                       label    = "colname of nominal time (NTIM)", 
                       choices  = colnames(tdata), 
                       multiple = FALSE,
                       width="100%", 
                       selected = ifelse("NTIM" %in% colnames(tdata), 
                                         "NTIM", 
                                         colnames(tdata)[1]
                                         )
                       ),
             
             textInput("xvar_name_label", label="label for NTIM", value="Nominal time (Day)"), 
             
             selectizeInput("id_name", 
                       label    = "colname of unique ID (USUBJID)", 
                       choices  = colnames(tdata), 
                       multiple = FALSE,
                       width="100%", 
                       selected = ifelse("USUBJID" %in% colnames(tdata), 
                                         "USUBJID", 
                                         colnames(tdata)[1]
                                         )
                       )
             ), 
      column(6,  
             selectizeInput("yvar_name", 
                       label    = "colname of dependent varaible (DVOR)", 
                       choices  = colnames(tdata), 
                       multiple = FALSE,
                       width="100%", 
                       selected = ifelse("DVOR" %in% colnames(tdata), 
                                         "DVOR", 
                                         colnames(tdata)[1]
                                         )
                       ),
             
             textInput("log_scale", label="logscale of DVOR", value="TRUE, FALSE, FALSE, FALSE"), 
             
             selectizeInput("dosegrp_name", 
                       label    = "colname of dose group (ARMA)", 
                       choices  = colnames(tdata), 
                       multiple = FALSE,
                       width="100%", 
                       selected = ifelse("ARMA" %in% colnames(tdata), 
                                         "ARMA", 
                                         colnames(tdata)[1]
                                         )
                       ),
             
             selectizeInput("testvar_name", 
                       label    = "colname of analyte (TEST)", 
                       choices  = colnames(tdata), 
                       multiple = FALSE,
                       width="100%", 
                       selected = ifelse("TEST" %in% colnames(tdata), 
                                         "TEST", 
                                         colnames(tdata)[1]
                                         )
                       )
          )
        )
      )
    ),
    
    fluidRow(
      column(12, 
        selectizeInput("multiple_test_name", 
                       label    = "select which variable(s)", 
                       choices  = TEST_lst, 
                       multiple = TRUE,
                       width="100%", 
                       selected = TEST_lst[1]),
      
       textInput("test_name_label", label="label for analyte name ", value="Concentration (mg/L)"), 
       style='margin-bottom:30px;  border:1px solid; padding: 10px;'
      )
    )
    
    ) # tagList
 })
  
 fluidRow(column(12, uiOutput(("select_multiple_response_variables_4PKPD_container"))))


```




```{r}  
 
output$PKPD_linked_profiles_plot <- renderUI({ 
  tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]]
  validate(need(tdata, message="no data found yet"))
    
  key_col_lst <- c("USUBJID", "ARMA","TIME", "NTIM", "TEST", "DVOR", "WGTBL")
  missing_cols <- setdiff(key_col_lst, colnames(tdata))
  validate(need(all(key_col_lst %in% colnames(tdata)), 
                message=paste0("missing key variable(s): ", paste0(missing_cols, collapse=","))
           )
  )
  
  col_lst <- c(key_col_lst, setdiff(colnames(tdata), key_col_lst))
  tdata = tdata %>% select(one_of(col_lst)) 
 
  ALL = callModule(module_linked_profiles, "module_PKPD_linked_profiles_plot", 
                    dataset = tdata, 
                    xvar_name = reactive(input$xvar_name), #"NTIM", 
                    xvar_name_label = 
                     if(length(input$xvar_name_label)==1) {
                                        reactive(rep(input$xvar_name_label,
                                                     times=length(input$multiple_test_name))
                                                 )
                                         }else{
                                         reactive(input$xvar_name_label)
                                      },
                    
                    yvar_name = reactive(input$yvar_name), 
                    test_name = reactive(input$multiple_test_name),  
                    test_name_label = if(length(input$test_name_label)==1) {
                                        reactive(rep(input$test_name_label,
                                                     times=length(input$multiple_test_name))
                                                 )
                                         }else{
                                         reactive(input$test_name_label)
                                      },
                   
                    log_scale = reactive(
                      as.logical(
                        eval(parse(text=paste0("c(", input$log_scale, ")")))
                        )
                      ),  
                    
                    id_name = reactive(input$id_name),  
                    dosegrp_name = reactive(input$dosegrp_name),
                    testvar_name = reactive(input$testvar_name) 
                        
   )
  
  # observeEvent(input$testvar_name, {
  #   
  # })
  
   module_linked_profiles_UI(("module_PKPD_linked_profiles_plot")) 
     
})

 fluidRow(column(12, uiOutput(("PKPD_linked_profiles_plot"))))

```



 
 
 
 
### PK-PD Sigmoid analysis 

Select which response variable for visualization. 


```{r}
values <- reactiveValues()
```

```{r}
  
  #--------------------------------------  
  # load_internal_ctlModel_container
  #-------------------------------------- 
  output$select_which_response_variable_4PKPD_container <- renderUI({
    validate(need(globalVars$login$status, message=FALSE)) 
    
    tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
    testcat.lst = unique(tdata$TESTCAT)
    testcat.lst = testcat.lst[which(substr(testcat.lst, 1, 4)=="RESP")]
   
    validate(need(tdata, message="no data found yet"), 
             need("TESTCAT" %in% colnames(tdata), message="missing TESTCAT variable"), 
             need(testcat.lst, message="no RESP variable found")
    )
   
    testcat.lst = c("", sort(testcat.lst) )
    
    fluidRow(
      column(12, 
        selectizeInput(("which_response_4PKPD"), 
                       label    = "select which response variable", 
                       choices  = testcat.lst, 
                       multiple = FALSE,
                       width="100%", 
                       selected = testcat.lst[1])
      )
    )
    
  })
  
 fluidRow(column(6, uiOutput(("select_which_response_variable_4PKPD_container"))))


```




```{r}
 
    
#PKPD_despcriptive_analysis_inputData <- reactive({
  observeEvent({input$which_response_4PKPD}, {
               
  tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
  validate(need(tdata, message="no data found yet"), 
           need(input$which_response_4PKPD, message=FALSE)
  )
  
 
  if ("TESTCAT" %in% colnames(tdata)) {
    # choose only PK and RESP
    values$data4_PKPD = tdata %>% filter(TESTCAT %in% c("PK", input$which_response_4PKPD)) %>% 
             mutate(TESTCAT = gsub(input$which_response_4PKPD, "RESP", TESTCAT, fix=TRUE))
  }
    
})
```








```{r}  
 
output$PKPD_despcriptive_analysis_plot <- renderUI({ 
  # Create a namespace function using the provided id
  #ns <- NS(id)
  
  validate(need(values$data4_PKPD, message="no data found yet"))
  
    # script = readLines(paste0(HOME, "/script/desp_sigmoid_PKPD.R"))
    # script = paste0(script, sep="\n")   # sep="<br/>")
    # script = paste0(script, collapse="")
    
  script <- list.files(path=paste0(HOME, "/script/"), 
                         full.names = TRUE,
                         pattern="despcriptive_PKPD")
  names(script) = basename(script)
    
   isolate({ 
      ALL = callModule(module_run_script, "PKPD_despcriptive_analysis_plot", 
                       ALL, 
                       dataset=values$data4_PKPD, 
                       script=script)
   }) 
  

   module_run_script_UI(("PKPD_despcriptive_analysis_plot"), label = NULL) 
     
})

 fluidRow(column(12, uiOutput(("PKPD_despcriptive_analysis_plot"))))

```
 

 

 