 
### Response  <a name="run_sim"></a>


#### Mean time-profile <a name="run_sim"></a>

Select which response variable for visualization. 
```{r}
  
  #--------------------------------------  
  # load_internal_ctlModel_container
  #-------------------------------------- 
  output$select_which_response_variable_container <- renderUI({
    validate(need(globalVars$login$status, message=FALSE)) 
    
    tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
    testcat.lst = unique(tdata$TESTCAT)
    testcat.lst = testcat.lst[which(substr(testcat.lst, 1, 4)=="RESP")]
   
    validate(need(tdata, message="no data found yet"), 
             need("TESTCAT" %in% colnames(tdata), message="missing TESTCAT variable"), 
             need(testcat.lst, message="no RESP variable found")
    )
   
    testcat.lst = c("", sort(testcat.lst) )
    
    fluidRow(
      column(6, 
        selectizeInput(("which_response"), 
                       label    = "select which response variable", 
                       choices  = testcat.lst, 
                       multiple = FALSE,
                       width="100%", 
                       selected = testcat.lst[1])
      )
    )
    
  })
  
 fluidRow(column(12, uiOutput(("select_which_response_variable_container"))))


```




```{r}
response_despcriptive_analysis_inputData <- reactive({
  tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
  validate(need(tdata, message="no data found yet"))
  
  if ("TESTCAT" %in% colnames(tdata)) {
    tdata = tdata %>% filter(TESTCAT==input$which_response)
  }
  
  print(head(tdata))
  tdata
  
})
```


```{r}  
 
output$response_despcriptive_analysis_population_mean_plot <- renderUI({ 
  # Create a namespace function using the provided id
  #ns <- NS(id)
  
  validate(need(response_despcriptive_analysis_inputData(), message="no data found yet"), 
           need(nrow(response_despcriptive_analysis_inputData())>0, message="data is empty")
  )
    # 
    # script = readLines(paste0(HOME, "/script/desp_mean_profile.R"))
    # script = paste0(script, sep="\n")   # sep="<br/>")
    # script = paste0(script, collapse="")
  
    
  script <- list.files(path=paste0(HOME, "/script/"), 
                         full.names = TRUE,
                         pattern="desp_mean_profile")
  names(script) = basename(script)
  
   isolate({ 
      ALL = callModule(module_run_script, "response_despcriptive_analysis_population_mean_plot", 
                       ALL, 
                       dataset=response_despcriptive_analysis_inputData(), 
                       script=script)
   }) 
  

   module_run_script_UI(("response_despcriptive_analysis_population_mean_plot"), label = NULL) 
     
})

 fluidRow(column(12, uiOutput(("response_despcriptive_analysis_population_mean_plot"))))

```
 


#### Individual time-profile <a name="run_sim"></a>



```{r}  
 
output$response_despcriptive_analysis_population_indiv_plot <- renderUI({ 
  # Create a namespace function using the provided id
  #ns <- NS(id)
  
  validate(need(response_despcriptive_analysis_inputData(), message="no data found yet"))
  
    script = readLines(paste0(HOME, "/script/desp_indiv_profile.R"))
    script = paste0(script, sep="\n")   # sep="<br/>")
    script = paste0(script, collapse="")
  
   isolate({ 
      ALL = callModule(module_run_script, "response_despcriptive_analysis_population_indiv_plot", 
                       ALL, 
                       dataset=response_despcriptive_analysis_inputData(), 
                       script=script)
   }) 
  

   module_run_script_UI(("response_despcriptive_analysis_population_indiv_plot"), label = NULL) 
     
})

 fluidRow(column(12, uiOutput(("response_despcriptive_analysis_population_indiv_plot"))))

```

