 
## PKPD relationship  <a name="run_sim"></a>

 
Select which response variable for visualization. 


```{r}
values <- reactiveValues()
```

```{r}
  
  #--------------------------------------  
  # load_internal_ctlModel_container
  #-------------------------------------- 
  output$select_which_response_variable_4PKPD_container <- renderUI({
    validate(need(globalVars$login$status, message=FALSE)) 
    
    tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
    testcat.lst = unique(tdata$TESTCAT)
    testcat.lst = testcat.lst[which(substr(testcat.lst, 1, 4)=="RESP")]
   
    validate(need(tdata, message="no data found yet"), 
             need("TESTCAT" %in% colnames(tdata), message="missing TESTCAT variable"), 
             need(testcat.lst, message="no RESP variable found")
    )
   
    testcat.lst = c("", sort(testcat.lst) )
    
    fluidRow(
      column(12, 
        selectizeInput(("which_response_4PKPD"), 
                       label    = "select which response variable", 
                       choices  = testcat.lst, 
                       multiple = FALSE,
                       width="100%", 
                       selected = testcat.lst[1])
      )
    )
    
  })
  
 fluidRow(column(6, uiOutput(("select_which_response_variable_4PKPD_container"))))


```




```{r}
 
    
#PKPD_despcriptive_analysis_inputData <- reactive({
  observeEvent({input$which_response_4PKPD}, {
               
  tdata = ALL$DATA[["mYtEsT_for_despcriptive_analysis"]] 
  validate(need(tdata, message="no data found yet"), 
           need(input$which_response_4PKPD, message=FALSE)
  )
  
 
  if ("TESTCAT" %in% colnames(tdata)) {
    # choose only PK and RESP
    values$data4_PKPD = tdata %>% filter(TESTCAT %in% c("PK", input$which_response_4PKPD)) %>% 
             mutate(TESTCAT = gsub(input$which_response_4PKPD, "RESP", TESTCAT, fix=TRUE))
    
    print("PKPD_despcriptive_analysis_inputData")
    print(head(values$data4_PKPD))
  }
    
})
```



 

 