---
title: "Untitled"
author: "Feng Yang"
date: "December 8, 2017"
output: word_document
---
 
# \@ref(discussion) Discussion {#discussion}
 
(to be finished)
  
The report should include a comprehensive statement of the rationale for model building
and reduction procedures, interpretation of the results, protocol violations, and discussion
and presentation of supporting graphs. The consequences of the modeling should also be
discussed (e.g., suggested dosing according to body weight, relationship of creatinine
clearance to drug clearance, and impact on special populations).

Cemiplimab concentration-time data obtained from doses of 1–10 mg/kg administered Q2W  were described adequately by a two-compartment model with zero-order IV infusion, first-order elimination (linear CL). The present analysis, which was restricted to data above 1 mg/kg, did not show an indication for nonlinearity in the clinical dose range. A parallel non-linear term for drug elimination did not improve the goodness-of-fit [23].  Goodness-of-fit plots showed no clear systematic trends or biases, confirming the adequacy of the model to describe the observed concentration-time profiles of cemiplimab. 

Following IV administration, Cemiplimab undergoes a biphasic elimination consisting of a rapid distribution phase and a slow elimination, with a derived steady-state terminal t1/2 of 25 days that is consistent with those seen for typical IgG therapeutics.35-37 Typical for a monoclonal antibody, cemiplimab has a low clearance (0.15 L/day), and a small volume of distribution consistent with limited distribution beyond extracellular space. Given the site of action of the drug on circulating T cells, this reflects sufficient availability of the drug to bind its target. Exchange between compartments was characterized by Q. The elimination half-life of cemiplimab derived from these primary PK parameters was 27.3 days. Overall, these characteristics are consistent with PK values for other therapeutic monoclonal antibodies , and result in a concentration-time profile that is amenable to maintaining clinically meaningful concentrations out to 3 weeks postdose (xxx).

The IIV in all model parameters was investigated in the development of the base model, and the simplification of the IIV structure (shared IIV on CL/Q, and V2/V3) enabled the establishment of a stable base model (as determined by condition number <1000 and correlation <0.95 in the parameter standard error matrix), which was essential for the robust estimation of covariate effects on PK parameters in the full model.

Trends of increasing concentrations beyond 20 weeks were visible in the VPC plot at the last portion of the concentration time curves; this was clearer for some treatment groups than for others. This can be explained by incorporation of time-varying CL which resulted in a statistically significant improvement in the goodness of fit, consistent with the finding observed in similar drugs [reference here].  Although there is no clear mechanistic understanding on time varying CL of cemiplimab, we hypothesize that the decrease in cemiplimab CL over the course of treatment may be associated with improvement in disease status, and the corresponding decrease in the rate of cancer related cachexia. Cachexia is a complex metabolic syndrome associated with underlying disease, characterized by loss of muscle mass due to hyper-metabolic state.28,29 One indicator of the level of cachexia and hyper-metabolic state is low serum albumin,28,30 which has been shown to be due to higher turnover in cachexic patients (and not due to a decrease in synthesis rate).31 The strong association between cemiplimab CL and ALB (Figure 2b) suggests that elimination or turnover of these proteins is higher in cachexic patients due to their hypermetabolic state. The higher rate of cemiplimab in putatively cachexic patients is consistent with reports of higher rates of whole body protein turnover in cancer patients.31 A decrease in cemiplimab CL may be indicative of decreased cachexia, and improvement in disease state.32,33

PPK model-based analysis provided a more robust assessment in special populations and reflects the totality of the effect of dose, and all covariates that have an effect on, compared with the covariate-effect plot which can show the one-dementional effect of covariates on PK model parameters.  BW, sex, and eGFR were found to be covariates that accounted for a portion of the IIV of REGN2810CL in the final PPK model, while only sex and BW accounted for a portion of the IIV on VC. The IIV for REGN2810on CL and VC was reduced by 30% and 21%, respectively, when these covariates were incorporated into the PPK model. Consistent with the mechanism of elimination for monoclonal antibodies, both CL and VC are higher in patients with higher BW.36 Although the PPK analysis showed that both CL and VC increase with BW, cemiplimab steady-state exposure (Cavgss, estimated with 400 dosing, allowing all patients to reach steady state) was comparable across the range of BW (34.1−168.2 kg) of the patients included in this PPK analysis dataset. The slight increase in exposure for patients with high BW is due to a less than proportional increase of CL as BW increases. During model development, it was found that PS and sex had a significant effect on REGN2810CL. The full PPK model showed that CL in patients with PS >0 appeared to be 19% higher compared to patients with PS of 0. CL in male patients appeared to be 18% higher relative to that of female patients, and CL in patients with Asian origin appeared to be 15% lower compared to white patients; however, the magnitude of PS, sex, and race effect were less than 20%, indicating that this effect was not clinically relevant. 

No clinically important differences in the CL and exposure of cemiplimab were found between patients with renal impairment and those with normal renal function. The full model showed that eGFR was unlikely to be a clinically relevant covariate, as the estimated change in CL in patients with renal impairment was within 20% (although the 95% CI was slightly lower at the 5th percentile of eGFR). However, during development of the final model, eGFR and race (Asian) were found to be a statistically significant covariate based on the BIC used to select the final model. Therefore, eGFR was included as a covariate on CL in the final model. The potential impact of renal impairment on cemiplimab exposure was also tested to determine whether there was a relationship between renal function and CL. The range of eGFR in the dataset covered the normal to moderate and had very few patients with severely impaired renal function based on the categorization of eGFR using the Chronic Kidney Disease Epidemiology Collaboration (CKD-EPI) equation. There was no relationship between renal function status and REGN2810CL and exposure, indicating that renal function has no impact on REGN2810PK. Furthermore, the absence of a relationship between eGFR and REGN2810CL is entirely consistent with renal physiology, as the large size of cemiplimab  (144 kDa) is expected to prevent it from being filtered through the glomeruli of the kidney and eliminated via the urine. 

The relatively modest covariate effects of about 20% in magnitude are not expected to be clinically significant. First, the safety and tolerability of cemiplimab have been established up to a dose level of 10 mg/kg Q2W, which is more than 3-fold higher than the recommended 3 mg/kg Q2W dose across indications. Second, exposure-response analysis of efficacy in multiple tumor types has shown that the exposure-response relationship is relatively flat for exposures produced by 3 mg/kg Q2W dosing regimen. Thus, these findings taken together indicate that no dose adjustment is warranted in patients with renal impairment. LDH data was not available in study CA209010 and CA209025, and serum albumin data were not available in study CA209037 and CA209066; therefore, their effects on cemiplimab were assessed in a sensitivity analysis. It was found that ALB level had a significant effect on CL (>20%), and cemiplimab was greater in patients with lower ALB levels (Figure 2b). Lower than normal albumin (<3.4 g/dL) could be a sign of liver or kidney disease, increased catabolic activity, or low neonatal Fc receptor expression level or activity. REGN2810exposures (dose-normalized Cavgss) in patients with lower than normal albumin were approximately 45% lower than in patients with normal albumin levels. Therefore, ALB was considered a potentially clinically relevant covariate for REGN2810PK. Furthermore, there appeared to be some correlation between PS and ALB, as albumin levels were found to be lower in patients with higher PS (correlation coefficient –0.27). It is likely that the potential effect of albumin on CL was represented to some extent by the effect of PS. 

Other covariates including age, LDH, mild hepatic impairment, and tumor type did not have clinically relevant (<20%) effects on REGN2810CL and were not included in the final PPK model. Further, a graphical assessment of baseline tumor burden, baseline tumor volume, and PD-L1 expression on REGN2810PK parameters showed that these factors have no impact on REGN2810PK.

In conclusion, this report presents the PPK model of cemiplimab PK data in patients with advanced malignancies, and demonstrates a similar level of cemiplimab exposure in both patients with CSCC and non-CSCC patients, with cemiplimab PK being linear with time-varying CL. Cemiplimab CL and VC increased with increasing BW, and flat dosing produced approximately similar cemiplimab exposures over the studied range of BW, compared to the BQ-normalized dosing regimens. The lack of effect of mild hepatic and renal impairment on cemiplimab PK suggests that dose adjustments was not required in these patient subpopulations.   Data were not available to extend these findings to severe renal impairment or moderate-to-severe hepatic impairment.
  
 
 
 
<!--
In the final model, REGN2810 CL decreases over time, with a mean maximal reduction from baseline values of approximately 24.5%. Following intravenous (IV) administration, REGN2810undergoes a biphasic elimination consisting of a rapid distribution phase with a geometric mean (coefficient of variation [CV] %) terminal half-life t½( of 32.5 hours (24.8%) and a slow elimination phase with a geometric mean (CV%) t½( of 25 days (77.5%) at steady state.



### \@ref(result-longitudinal-clearance-implication) Longitudinal clearance  {#result-longitudinal-clearance-implication}
  

Incorporation of these covariates in the final model explained approximately 24% and 52% of the base model variability of CL and Vc, respectively.

The change in CL with time was evaluated by comparing the goodness of fit of models incorporating hyperbolic and sigmoid Emax temporal changes in CL with that of a model with constant CL. The BIC values of both hyperbolic and sigmoid Emax models were markedly lower than that of the model with constant CL, indicating that the models with time-varying CL provided a better description of the data . The magnitude of the decrease in BIC was greatest with the sigmoid-Emax model, indicating that the temporal change in CL was best described by this modelcemiplimab CL decreases over time with approximately 25% maximal reduction from baseline values. The final PPK model was evaluated using VPC, which showed that the linear two-compartment model with zero-order infusion adequately characterized the data. 


	Figure 1a-1b: complete and partial responders showed greatest decrease in CL of anti-PD1 from baseline.
	Figure 1c-1d: Longitudinal decrease in anti-PD1 CL with time. Asymptote reached at 6 months after therapy 
	(steady state).  This effect is more pronounced in CR and PR (responders) compared to SD and PD (non-responders).
	These figures illustrate the time-dependent change of anti-PD1 CL with disease progression (disease-PK interaction).
The mechanism of action of cemiplimab, binding to PD-1 receptors on T cells, does not depend on direct engagement of the molecule with tumor cells. For this reason, substantial differences in exposure–response and dose– response are not expected.  Meanwhile, in clinical development of cemiplimab, the majority of data were collected from dosing regimens (3 mg/kg, Q2W). As a result, dose-response may not be applicable. 


-->
  
