---
title: "Untitled"
author: "Feng Yang"
date: "December 21, 2017"
output: word_document
---

 
## \@ref(sec-appendix-D)	Appendix D Final Model (Additional Figures/Tables) {#sec-appendix-D}


### \@ref(sec-diagnostic-final-model)	Diagnostic Plots for Final Model {#sec-diagnostic-final-model}



```{r diagnostic-plot-final-model, fig.cap='Conditional residue (CWRES) versus time, individual prediction (IPRED), subject ID, and theoretical quantiles from the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
  
runno = final.model.runno     # "LN014" # "LN001"
OUTPUT = read_OUTPUT(MODEL.HOME, subdir="/ctl/HPC/", runno, adpx00)

tdata = OUTPUT[[runno]]  %>% filter(EVID==0)  %>% mutate(CWRES=as_numeric(CWRES), 
                                                         IWRES=as_numeric(IWRES),
                                                         ID=as.integer(as.factor(USUBJID)))

fig = GOF2(tdata)
fig <- recordPlot()
FIGURE_ALL[["diagnostic_plot_final_model"]] = fig


fig
  
```







<br>

```{r AGEvsETA, fig.cap='Age as covariate impacting on model parameters in the final Model', fig.align='center', out.width='80%', fig.asp=.75}
  
runno = final.model.runno     # "LN014" # "LN001"
#OUTPUT = read_OUTPUT(MODEL.HOME, subdir="/ctl/HPC/", runno, adpx00)

tdata = OUTPUT[[runno]]  %>% filter(EVID==0)  %>% mutate(CWRES=as_numeric(CWRES), 
                                                         IWRES=as_numeric(IWRES),
                                                         ID=as.integer(as.factor(USUBJID)))

    
ETA.lst = colnames(tdata)[which(substr(colnames(tdata), 1, 3)=="ETA")]  

fig = ETAvsCOV(tdata, cov_name=c("AGE" ),  eta_name=ETA.lst)  
FIGURE_ALL[["AGEvsETA"]] = fig


fig
  
```

<br>

```{r WGTBLvsETA, fig.cap='Baseline body weight as covariate impacting on model parameters in the final Model', fig.align='center', out.width='80%', fig.asp=.75}
fig = ETAvsCOV(tdata, cov_name=c("WGTBL" ),  eta_name=ETA.lst)  
FIGURE_ALL[["WGTBLvsETA"]] = fig


fig
```

<br>

```{r ALBBLvsETA, fig.cap='Baseline albumin as covariate impacting on model parameters in the final Model', fig.align='center', out.width='80%', fig.asp=.75}
fig = ETAvsCOV(tdata, cov_name=c("ALBBL" ),  eta_name=ETA.lst)  
FIGURE_ALL[["ALBBLvsETA"]] = fig


fig
```

<br>



```{r IGGBLvsETA, fig.cap='Baseline IGG level as covariate impacting on model parameters in the final Model', fig.align='center', out.width='80%', fig.asp=.75}


fig = ETAvsCOV(tdata, cov_name=c("IGGBL" ),  eta_name=ETA.lst)  

FIGURE_ALL[["IGGBLvsETA"]] = fig


fig
```

<br>




```{r  boxplot-RACE-CL, fig.cap='Boxplot Showing the Relationship between Race and Cimiplimab Clearance Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}



runno = final.model.runno     # "LN014" # "LN001"
#OUTPUT = read_OUTPUT(MODEL.HOME, subdir="/ctl/HPC/", runno, adpx00)

tdata = OUTPUT[[runno]]  %>% filter(EVID==0)  %>% mutate(CWRES=as_numeric(CWRES), 
                                                         IWRES=as_numeric(IWRES),
                                                         ID=as.integer(as.factor(USUBJID)))
tdata = tdata %>% mutate(CL=as_numeric(CL), 
                         EMAX=as_numeric(EMAX), 
                         T50 = as_numeric(T50)  )
   
unique(tdata$RACE)
t1 = tdata %>% filter(RACE%in% c("WHITE", "ASIAN", "BLACK OR AFRICAN AMERICAN")) %>% 
     mutate(CL=as_numeric(CL)) %>% 
     filter(!is.na(CL))

tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(RACE)  %>% table() %>% as.data.frame()
colnames(tt) = c("RACE", "FREQ")
 
t1 = noWarning(t1 %>% left_join(tt, by="RACE") %>% mutate(RACE=paste0(RACE, "(", FREQ, ")")))
 
fig = noWarning(cat_boxplot(t1, xvar="RACE", yvar="CL" ) )
FIGURE_ALL[["boxplot_RACE_CL"]] = fig


fig

   

```

```{r boxplot-RACE-ON-EMAX, fig.cap='Boxplot Showing the Relationship between Race and Emax Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
   
unique(tdata$RACE)
t1 = tdata %>% filter(RACE%in% c("WHITE", "ASIAN", "BLACK OR AFRICAN AMERICAN"))%>% 
  mutate(EMAX=as_numeric(EMAX)) %>% 
     filter(!is.na(EMAX))
tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(RACE)  %>% table() %>% as.data.frame()
colnames(tt) = c("RACE", "FREQ")
 
t1 = noWarning(t1 %>% left_join(tt, by="RACE") %>% mutate(RACE=paste0(RACE, "(", FREQ, ")")))
 
fig=noWarning(cat_boxplot(t1, xvar="RACE", yvar="EMAX" ) )
 FIGURE_ALL[["boxplot_RACE_EMAX"]] = fig


fig

```



```{r boxplot-RACE-ON-T50, fig.cap='Boxplot Showing the Relationship between Race and T50 Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
   

unique(tdata$RACE)
t1 = tdata %>% filter(RACE%in% c("WHITE", "ASIAN", "BLACK OR AFRICAN AMERICAN"))%>% 
  mutate(T50=as_numeric(T50)) %>% 
     filter(!is.na(T50))
tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(RACE)  %>% table() %>% as.data.frame()
colnames(tt) = c("RACE", "FREQ")
 
t1 = noWarning(t1 %>% left_join(tt, by="RACE") %>% mutate(RACE=paste0(RACE, "(", FREQ, ")")))
 
fig = noWarning(cat_boxplot(t1, xvar="RACE", yvar="T50" ) )
FIGURE_ALL[["boxplot_RACE_T50"]] = fig


fig   


```

```{r boxplot-CSCC-ON-CL, fig.cap='Boxplot Showing the Relationship between CSCC or non-CSCC patients and Cimiplimab Clearance Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
   
unique(tdata$CSCCP2F)
t1 = tdata %>%  mutate(CL=as_numeric(CL)) %>%  filter(!is.na(CL))
tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(CSCCP2F)  %>% table() %>% as.data.frame()
colnames(tt) = c("CSCCP2F", "FREQ")
 
t1 = noWarning(t1 %>% left_join(tt, by="CSCCP2F") %>% mutate(CSCCP2F=paste0(CSCCP2F, "(", FREQ, ")")))
 
fig = noWarning(cat_boxplot(t1, xvar="CSCCP2F", yvar="CL" ) )
   
FIGURE_ALL[["boxplot_CSCC_CL"]] = fig


fig
```




```{r boxplot-CSCC-ON-EMAX, fig.cap='Boxplot Showing the Relationship between CSCC or non-CSCC patients and Emax Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
   
unique(tdata$CSCCP2F)
t1 = tdata %>%   mutate(EMAX=as_numeric(EMAX)) %>%   filter(!is.na(CL))
tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(CSCCP2F)  %>% table() %>% as.data.frame()
colnames(tt) = c("CSCCP2F", "FREQ")
 
t1 = noWarning(t1 %>% left_join(tt, by="CSCCP2F") %>% mutate(CSCCP2F=paste0(CSCCP2F, "(", FREQ, ")")))
 
fig = noWarning(cat_boxplot(t1, xvar="CSCCP2F", yvar="EMAX" ) )
   FIGURE_ALL[["boxplot_CSCC_EMAX"]] = fig


fig

```









```{r boxplot-IGGBL-ON-CL, fig.cap='Boxplot Showing the Relationship between Baseline IGG and Cemiplimab Clearance Using the Final Model', fig.align='center', out.width='80%', fig.asp=.75}
    

runno = final.model.runno     # "LN014" # "LN001"
#OUTPUT = read_OUTPUT(MODEL.HOME, subdir="/ctl/HPC/", runno, adpx00)

tdata = OUTPUT[[runno]]  %>% filter(EVID==0, C==".")  %>% mutate(CWRES=as_numeric(CWRES), 
                                                         IWRES=as_numeric(IWRES),
                                                         ID=as.integer(as.factor(USUBJID)))

t1 =tdata %>% distinct(USUBJID, .keep_all=TRUE) %>% 
       mutate(IGGBL=as_numeric(IGGBL)) %>%   
       assign_Q(value="IGGBL", quartile=c(0, 0.25, 0.5, 0.75, 1), breaks=NULL, 
                       include.lowest = TRUE, right = TRUE, ordered_result = FALSE) 

t1 =  t1 %>% #select(CL, ALBBL, Q_LABEL, Quantile) %>% 
        mutate(Q_LABEL=paste0("IGGBL=", Q_LABEL))
  
t1 = t1 %>% arrange(Quantile) %>% mutate(Q_LABEL=ordered(Q_LABEL, levels=unique(Q_LABEL)))
#t1 = tdata %>% mutate(HIGH.ALBBL=ifelse(ALBBL>median(ALBBL, na.rm=TRUE), "High Baseline Albumin", "Low Baseline Albumin"))
# 
# tt = t1 %>% distinct(USUBJID, .keep_all=TRUE) %>% pull(HIGH.ALBBL)  %>% table() %>% as.data.frame()
# colnames(tt) = c("HIGH.ALBBL", "FREQ")
#  
# t1 = noWarning(t1 %>% left_join(tt, by="HIGH.ALBBL") %>% mutate(HIGH.ALBBL=paste0(HIGH.ALBBL, "(", FREQ, ")")))
 
t1 = t1 %>% mutate(CL=as_numeric(CL))
fig = noWarning(cat_boxplot(t1, xvar="Q_LABEL", yvar="CL", theTitle="Impact of baseline IGGBL on CL") )
   

FIGURE_ALL[["boxplot_IGGBL_CL"]] = fig


fig


```







 
 
 


    
```{r ALB-VS-TIME, fig.cap='Albumin vs Time in Both Study-1423 and Study-1540', fig.align='center', out.width='80%', fig.asp=.75}    

tdata = adpx0 %>% filter(EVID==0, TIME>=0)
tdata = tdata %>% mutate(TIME=as_numeric(TIME), 
                         ALB=as_numeric(ALB), 
                         ALBBL= as_numeric(ALBBL), 
                         ALB.PCHG = (ALB-ALBBL)/ALBBL*100  )

tdata = tdata %>% mutate(DVOR=ALB.PCHG)
tdata = tdata %>% filter(TIME>=0, !is.na(DVOR))
 
fig = ggplot(tdata, aes(x= TIME, y=DVOR)) + geom_point() + 
  stat_smooth(method = "loess", color = "blue", se = F, size = 1.3) + 
  xlab("Time (day)") + 
  ylab("Percent Change from baseline (Albumin)") + 
  base_theme(font.size=14) + 
  theme(legend.position='none', 
        panel.grid.minor= element_line(colour = "gray95",size=0.5),
        panel.grid.major= element_line(colour = "gray95",size=0.5),
        panel.spacing = unit(0.2, "lines"), 
        panel.border=element_rect(colour="black", fill=NA), 
        strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
  ) #+ facet_wrap(~factor(PARAMCD ), ncol = 2)
 
 
# tt = tdata %>% mutate(NTIM=as_numeric(NTIM)) %>% group_by(NTIM) %>% summarise(Mean=mean(DVOR,na.rm=TRUE))
# ggplot(tt, aes(x=NTIM, y=Mean)) + geom_line(col="red", lwd=2) + 
#   geom_point(data=tdata, aes(TIME, DVOR)) 
FIGURE_ALL[["ALB_vs_TIME"]] = fig


fig


```
     

    
```{r WGT-VS-TIME}    

tdata = adpx0 %>% filter(EVID==0, TIME>=0)
tdata = tdata %>% mutate(TIME=as_numeric(TIME), 
                         WGT=as_numeric(WGT), 
                         WGTBL= as_numeric(WGTBL), 
                         WGT.PCHG = (WGT-WGTBL)/WGTBL*100  )

tdata = tdata %>% mutate(DVOR=WGT.PCHG)
tdata = tdata %>% filter(TIME>=0, !is.na(DVOR))
 
fig = ggplot(tdata, aes(x= TIME, y=DVOR)) + geom_point() + 
  stat_smooth(method = "loess", color = "blue", se = F, size = 1.3) + 
  xlab("Time (day)") + 
  ylab("Percent Change from baseline (Body Weight)") + 
  base_theme(font.size=14) + 
  theme(legend.position='none', 
        panel.grid.minor= element_line(colour = "gray95",size=0.5),
        panel.grid.major= element_line(colour = "gray95",size=0.5),
        panel.spacing = unit(0.2, "lines"), 
        panel.border=element_rect(colour="black", fill=NA), 
        strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
  ) #+ facet_wrap(~factor(PARAMCD ), ncol = 2)
 
FIGURE_ALL[["WGT_vs_TIME"]] = fig


fig
 


```




```{r LDH-VS-TIME}    

tdata = adpx0 %>% filter(EVID==0, TIME>=0)
tdata = tdata %>% mutate(TIME=as_numeric(TIME), 
                         LDH=as_numeric(LDH), 
                         LDHBL= as_numeric(LDHBL), 
                         LDH.PCHG = (LDH-LDHBL)/LDHBL*100  )

tdata = tdata %>% mutate(DVOR=LDH.PCHG)
tdata = tdata %>% filter(TIME>=0, !is.na(DVOR), abs(DVOR)<200)
 
fig = ggplot(tdata, aes(x= TIME, y=DVOR)) + geom_point() + 
  stat_smooth(method = "loess", color = "blue", se = F, size = 1.3) + 
  xlab("Time (day)") + 
  ylab("Percent Change from baseline (Body Weight)") + 
  base_theme(font.size=14) + 
  theme(legend.position='none', 
        panel.grid.minor= element_line(colour = "gray95",size=0.5),
        panel.grid.major= element_line(colour = "gray95",size=0.5),
        panel.spacing = unit(0.2, "lines"), 
        panel.border=element_rect(colour="black", fill=NA), 
        strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
  ) #+ facet_wrap(~factor(PARAMCD ), ncol = 2)
 
 
FIGURE_ALL[["LDH_vs_TIME"]] = fig


fig


```

<br>
<br>

```{r hist-mofv-1000, fig.cap='Histogram of Minimum Objective Values across 1,000 Bootstrap Runs', fig.align='center', out.width='80%', fig.asp=.75}  

  tdata = PARAMS1000 
  
  #tdata$minimization_successful
   
 tdata$GROUP= "NONE"
 fig = base_hist(tdata, xval="ofv", group="GROUP", binwidth=100, title=NULL, xlab.txt="MOFV") + 
   #xlab("Time (day)") + 
  # ylab("Concentration (mg/L)") + 
   base_theme(font.size=14) + 
     #scale_x_continuous(breaks=x$breaks, label=x$labels) + 
     #scale_y_log10(breaks=y$breaks, label=y$labels) + 
  
     #coord_cartesian(xlim = range(tdata$TIME, na.rm=TRUE)) + 
     #coord_cartesian(ylim = range(tdata$DVOR, na.rm=TRUE)) + 
     
   theme(#legend.title=element_text("EXSEQ"), 
         legend.position="none", 
         panel.grid.minor= element_line(colour = "gray95",size=0.5),
         panel.grid.major= element_line(colour = "gray95",size=0.5),
         panel.spacing = unit(0.2, "lines"), 
         panel.border=element_rect(colour="black", fill=NA), 
         strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
   )
 
 FIGURE_ALL[["hist_ofv_1000"]] = fig
 
 fig
 
 
 
```
  

```{r hist-CL-1000, fig.cap='Histogram of Parameter Estimates (CL) across 1,000 Bootstrap Runs', fig.align='center', out.width='80%', fig.asp=.75}  

  tdata = PARAMS1000 %>% as.data.frame()
  
  #tdata$minimization_successful
   
 xval="TVCL"
 xlab = "Clerance (L/day)"
 tdata$GROUP= "NONE"
 tdata[, xval] = as_numeric(tdata[, xval])
 fig = base_hist(tdata, xval=xval, group="GROUP", binwidth=0.002, title=NULL, xlab.txt=xlab) + 
   #xlab("Time (day)") + 
  # ylab("Concentration (mg/L)") + 
   base_theme(font.size=14) + 
     #scale_x_continuous(breaks=x$breaks, label=x$labels) + 
     #scale_y_log10(breaks=y$breaks, label=y$labels) + 
  
     #coord_cartesian(xlim = range(tdata$TIME, na.rm=TRUE)) + 
     #coord_cartesian(ylim = range(tdata$DVOR, na.rm=TRUE)) + 
     
   theme(#legend.title=element_text("EXSEQ"), 
         legend.position="none", 
         panel.grid.minor= element_line(colour = "gray95",size=0.5),
         panel.grid.major= element_line(colour = "gray95",size=0.5),
         panel.spacing = unit(0.2, "lines"), 
         panel.border=element_rect(colour="black", fill=NA), 
         strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
   )
 
 FIGURE_ALL[["hist_CL_1000"]] = fig
 
 fig
 
 
 
```




```{r hist-V2-1000, fig.cap='Histogram of Parameter Estimates (V2) across 1,000 Bootstrap Runs', fig.align='center', out.width='80%', fig.asp=.75}  

  tdata = PARAMS1000 %>% as.data.frame()
  
  #tdata$minimization_successful
   
 xval="TVV2"
 xlab = "Volume of Central Compartment (V2, L)"
 tdata$GROUP= "NONE"
 tdata[, xval] = as_numeric(tdata[, xval])
 fig = base_hist(tdata, xval=xval, group="GROUP", binwidth=0.01, title=NULL, xlab.txt=xlab) + 
   #xlab("Time (day)") + 
  # ylab("Concentration (mg/L)") + 
   base_theme(font.size=14) + 
     #scale_x_continuous(breaks=x$breaks, label=x$labels) + 
     #scale_y_log10(breaks=y$breaks, label=y$labels) + 
  
     #coord_cartesian(xlim = range(tdata$TIME, na.rm=TRUE)) + 
     #coord_cartesian(ylim = range(tdata$DVOR, na.rm=TRUE)) + 
     
   theme(#legend.title=element_text("EXSEQ"), 
         legend.position="none", 
         panel.grid.minor= element_line(colour = "gray95",size=0.5),
         panel.grid.major= element_line(colour = "gray95",size=0.5),
         panel.spacing = unit(0.2, "lines"), 
         panel.border=element_rect(colour="black", fill=NA), 
         strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
   )
 
 FIGURE_ALL[["hist_V2_1000"]] = fig
 
 fig
 
 
 
```


```{r hist-Emax-1000, fig.cap='Histogram of Parameter Estimates (Emax) across 1,000 Bootstrap Runs', fig.align='center', out.width='80%', fig.asp=.75}  

  tdata = PARAMS1000 %>% as.data.frame()
  
  #tdata$minimization_successful
   
 xval="EMAX"
 xlab = "Maximum Clearance Reduction (Emax, unitless)"
 tdata$GROUP= "NONE"
 tdata[, xval] = as_numeric(tdata[, xval])
 fig = base_hist(tdata, xval=xval, group="GROUP", binwidth=0.01, title=NULL, xlab.txt=xlab) + 
   #xlab("Time (day)") + 
  # ylab("Concentration (mg/L)") + 
   base_theme(font.size=14) + 
     #scale_x_continuous(breaks=x$breaks, label=x$labels) + 
     #scale_y_log10(breaks=y$breaks, label=y$labels) + 
  
     #coord_cartesian(xlim = range(tdata$TIME, na.rm=TRUE)) + 
     #coord_cartesian(ylim = range(tdata$DVOR, na.rm=TRUE)) + 
     
   theme(#legend.title=element_text("EXSEQ"), 
         legend.position="none", 
         panel.grid.minor= element_line(colour = "gray95",size=0.5),
         panel.grid.major= element_line(colour = "gray95",size=0.5),
         panel.spacing = unit(0.2, "lines"), 
         panel.border=element_rect(colour="black", fill=NA), 
         strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
   )
 
 FIGURE_ALL[["hist_Emax_1000"]] = fig
 
 fig
 
 
 
```



```{r hist-T50-1000, fig.cap='Histogram of Parameter Estimates (T50) across 1,000 Bootstrap Runs', fig.align='center', out.width='80%', fig.asp=.75}  

  tdata = PARAMS1000 %>% as.data.frame()
  
  #tdata$minimization_successful
   
 xval="T50"
 xlab = "Half-life to Achieve Maximum Clearance Reduction (T50, unitless)"
 tdata$GROUP= "NONE"
 tdata[, xval] = as_numeric(tdata[, xval])
 fig = base_hist(tdata, xval=xval, group="GROUP", binwidth=1, title=NULL, xlab.txt=xlab) + 
   #xlab("Time (day)") + 
  # ylab("Concentration (mg/L)") + 
   base_theme(font.size=14) + 
     #scale_x_continuous(breaks=x$breaks, label=x$labels) + 
     #scale_y_log10(breaks=y$breaks, label=y$labels) + 
  
     #coord_cartesian(xlim = range(tdata$TIME, na.rm=TRUE)) + 
     #coord_cartesian(ylim = range(tdata$DVOR, na.rm=TRUE)) + 
     
   theme(#legend.title=element_text("EXSEQ"), 
         legend.position="none", 
         panel.grid.minor= element_line(colour = "gray95",size=0.5),
         panel.grid.major= element_line(colour = "gray95",size=0.5),
         panel.spacing = unit(0.2, "lines"), 
         panel.border=element_rect(colour="black", fill=NA), 
         strip.background = element_blank()   # element_rect(colour=NA, fill=NA),
   )
 
 FIGURE_ALL[["hist_T50_1000"]] = fig
 
 fig
 
 
 
```



```{r  }

runno = final.model.runno     # "LN014" # "LN001"
OUTPUT = read_OUTPUT(MODEL.HOME, subdir="/ctl/HPC/", runno, adpx00)

tdata = OUTPUT[[runno]]  %>% filter(EVID==0)  %>% mutate(CWRES=as_numeric(CWRES), 
                                                         IWRES=as_numeric(IWRES),
                                                         DVOR =as_numeric(DVOR),
                                                         PRED=as_numeric(PRED), 
                                                         IPRED=as_numeric(IPRED),
                                                         TIME=as_numeric(TIME),
                                                         ID=as.integer(as.factor(USUBJID)))


tdata = tdata %>% filter(TIME<56, ID %in% sample(tdata$ID, 25)) 

fig = ggplot(tdata, aes(x=TIME, y=DVOR, group=USUBJID)) + geom_point()  + 
   geom_line(aes(x=TIME, PRED, group=USUBJID), col="blue") + 
   geom_line(aes(x=TIME, IPRED, group=USUBJID), col="green") + 
   scale_y_log10() + facet_wrap(~ID, ncol=5) + 
   xlab("Time (day)") + 
   ylab("Concentration (mg/L)")  + 
  base_theme(font.size=14)   + 
 facet_wrap(~ID, ncol=5)


fig
 

FIGURE_ALL[["Final_RepresentiveFit_25"]] = fig
 
 fig
 



```







 

  